### ISSUE TITLE
fix some plots going to zero

### ISSUE THREAD

**Issue by djay** [djay/covidthailand#66]
![image](https://user-images.githubusercontent.com/41700/133964987-e9e90ee3-49a7-46b3-8bfb-2b76e09b923c.png)
![image](https://user-images.githubusercontent.com/41700/133965032-4e873889-9b06-4b23-8036-e1e419f8f9bb.png)

**Comment by reduxionist** [comment]
Was this what you fixed with 3cc5592 @djay?

**Comment by djay** [comment]
Sorry yes that fixes the province top plot. But it doesn't fix the server cases plot.
btw, things going to zero are often caused by operations like sum which by default will turn ignore nan.

**Comment by reduxionist** [comment]
Ah, thus this is still open. Thanks for the explanation! :)

**Comment by djay** [comment]
I think this pretty much fixed now
